name: build

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - alpine-arm64
          - alpine-x64
          - beige-loong64
          - beige-devtoolset-loong64
          # - bionic-devtoolset-ppc64le
          - focal-arm64
          - focal-armhf
          - focal-ppc64le
          - focal-riscv64
          - focal-x64
          - focal-devtoolset-arm64
          - focal-devtoolset-armhf
          - focal-devtoolset-ppc64le
          - focal-devtoolset-riscv64
          - focal-devtoolset-s390x
          - focal-devtoolset-x64

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
        if: "!endsWith(matrix.arch, 'x64') && !endsWith(matrix.arch, 'loong64')"

      - name: Set up QEMU for Loong64
        run: docker run --rm --privileged loongcr.lcpu.dev/multiarch/archlinux --reset -p yes
        if: "endsWith(matrix.arch, 'loong64')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.arch }}
          file: ${{ matrix.arch }}/Dockerfile
          tags: vscodium/vscodium-linux-build-agent:${{ matrix.arch }}
          push: ${{ github.ref == 'refs/heads/master' }}
